Event - 10/03/2023 10:23:49 - Get Rss Feeds And Send Http Request For Information About News
Exception - 10/03/2023 10:23:57 -    at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Commit(DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityTransaction.Commit()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 160
   at News.Entity.Websites.Globes.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\Websites\Globes.cs:line 58, An error was reported while committing a database transaction but it could not be determined whether the transaction succeeded or failed on the database server. See the inner exception and http://go.microsoft.com/fwlink/?LinkId=313468 for more information.
Event - 10/03/2023 11:48:04 - Get Rss Feeds And Send Http Request For Information About News
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 59, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 59, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 59, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.Websites.Globes.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\Websites\Globes.cs:line 63, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 59, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.Websites.Globes.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\Websites\Globes.cs:line 63, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 59, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.Websites.Globes.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\Websites\Globes.cs:line 63, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 59, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.Websites.Globes.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\Websites\Globes.cs:line 63, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 59, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.Websites.Globes.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\Websites\Globes.cs:line 63, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Exception - 10/03/2023 11:48:05 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 59, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Event - 10/03/2023 12:22:36 - Get Rss Feeds And Send Http Request For Information About News
Exception - 10/03/2023 12:22:37 -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 52, An error occurred while executing the command definition. See the inner exception for details.
Exception - 10/03/2023 12:22:37 -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 52, An error occurred while executing the command definition. See the inner exception for details.
Exception - 10/03/2023 12:22:37 -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 52, An error occurred while executing the command definition. See the inner exception for details.
Event - 10/03/2023 12:48:07 - Get Rss Feeds And Send Http Request For Information About News
Exception - 10/03/2023 12:48:08 -    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at News.DAL.Repository`1.Insert(TEntity entity) in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 148
   at News.Entity.RssFeedExtraction.FeedExtraction(XmlDocument xmlDoc, Category category) in C:\Users\User\source\repos\News\News.Entity\RssFeedExtraction.cs:line 61, Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Event - 10/03/2023 12:51:12 - Get Rss Feeds And Send Http Request For Information About News
Event - 10/03/2023 14:43:51 - Get Rss Feeds And Send Http Request For Information About News
Event - 10/03/2023 14:50:05 - Get Rss Feeds And Send Http Request For Information About News
Event - 10/03/2023 15:05:00 - Get Rss Feeds And Send Http Request For Information About News
Event - 10/03/2023 15:15:44 - Get Rss Feeds And Send Http Request For Information About News
Event - 10/03/2023 19:15:41 - Get Rss Feeds And Send Http Request For Information About News
Exception - 10/03/2023 19:15:41 -    at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at News.API.Controllers.UserController.AddUserToDB(String email) in C:\Users\User\source\repos\News\News.API\Controllers\UserController.cs:line 19, The underlying provider failed on Open.
Event - 10/03/2023 19:30:21 - Get Rss Feeds And Send Http Request For Information About News
Exception - 10/03/2023 19:30:21 -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at News.DAL.Repository`1.GetAll() in C:\Users\User\source\repos\News\News.DAL\CRUD.cs:line 61
   at News.API.Controllers.CategoryController.GetAllCategories() in C:\Users\User\source\repos\News\News.API\Controllers\CategoryController.cs:line 19, An error occurred while executing the command definition. See the inner exception for details.
Event - 10/03/2023 20:07:13 - Get Rss Feeds And Send Http Request For Information About News
Exception - 10/03/2023 20:07:13 -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at News.API.Controllers.UserController.AddUserToDB(String email) in C:\Users\User\source\repos\News\News.API\Controllers\UserController.cs:line 19, An error occurred while executing the command definition. See the inner exception for details.
Exception - 10/03/2023 20:07:29 -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at News.API.Controllers.UserController.GetUserCategories(String email) in C:\Users\User\source\repos\News\News.API\Controllers\UserController.cs:line 75, An error occurred while executing the command definition. See the inner exception for details.
Exception - 10/03/2023 20:07:42 -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at News.API.Controllers.UserController.GetUserCategories(String email) in C:\Users\User\source\repos\News\News.API\Controllers\UserController.cs:line 75, An error occurred while executing the command definition. See the inner exception for details.
